// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/pb_message.proto

package com.whosbean.qpush.protobuf;

public final class PbMessage {
  private PbMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_message_PBAPNSUserInfo_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_PBAPNSUserInfo_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_message_PBAPNSBody_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_PBAPNSBody_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_message_PBAPNSMessage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_PBAPNSMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031protobuf/pb_message.proto\022\007message\",\n\016" +
      "PBAPNSUserInfo\022\013\n\003key\030\001 \002(\t\022\r\n\005value\030\002 \002" +
      "(\t\"9\n\nPBAPNSBody\022\r\n\005alert\030\001 \001(\t\022\r\n\005sound" +
      "\030\002 \001(\t\022\r\n\005badge\030\003 \001(\005\"\\\n\rPBAPNSMessage\022 " +
      "\n\003aps\030\001 \002(\0132\023.message.PBAPNSBody\022)\n\010user" +
      "Info\030\002 \003(\0132\027.message.PBAPNSUserInfoB\037\n\033c" +
      "om.whosbean.qpush.protobufP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_message_PBAPNSUserInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_message_PBAPNSUserInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_message_PBAPNSUserInfo_descriptor,
              new java.lang.String[] { "Key", "Value", });
          internal_static_message_PBAPNSBody_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_message_PBAPNSBody_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_message_PBAPNSBody_descriptor,
              new java.lang.String[] { "Alert", "Sound", "Badge", });
          internal_static_message_PBAPNSMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_message_PBAPNSMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_message_PBAPNSMessage_descriptor,
              new java.lang.String[] { "Aps", "UserInfo", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
