// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/pb_message.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "protobuf/pb_message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace message {

namespace {

const ::google::protobuf::Descriptor* PBAPNSUserInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PBAPNSUserInfo_reflection_ = NULL;
const ::google::protobuf::Descriptor* PBAPNSBody_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PBAPNSBody_reflection_ = NULL;
const ::google::protobuf::Descriptor* PBAPNSMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PBAPNSMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_protobuf_2fpb_5fmessage_2eproto() {
  protobuf_AddDesc_protobuf_2fpb_5fmessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "protobuf/pb_message.proto");
  GOOGLE_CHECK(file != NULL);
  PBAPNSUserInfo_descriptor_ = file->message_type(0);
  static const int PBAPNSUserInfo_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBAPNSUserInfo, key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBAPNSUserInfo, value_),
  };
  PBAPNSUserInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PBAPNSUserInfo_descriptor_,
      PBAPNSUserInfo::default_instance_,
      PBAPNSUserInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBAPNSUserInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBAPNSUserInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PBAPNSUserInfo));
  PBAPNSBody_descriptor_ = file->message_type(1);
  static const int PBAPNSBody_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBAPNSBody, alert_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBAPNSBody, sound_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBAPNSBody, badge_),
  };
  PBAPNSBody_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PBAPNSBody_descriptor_,
      PBAPNSBody::default_instance_,
      PBAPNSBody_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBAPNSBody, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBAPNSBody, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PBAPNSBody));
  PBAPNSMessage_descriptor_ = file->message_type(2);
  static const int PBAPNSMessage_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBAPNSMessage, aps_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBAPNSMessage, userinfo_),
  };
  PBAPNSMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PBAPNSMessage_descriptor_,
      PBAPNSMessage::default_instance_,
      PBAPNSMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBAPNSMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBAPNSMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PBAPNSMessage));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_protobuf_2fpb_5fmessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PBAPNSUserInfo_descriptor_, &PBAPNSUserInfo::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PBAPNSBody_descriptor_, &PBAPNSBody::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PBAPNSMessage_descriptor_, &PBAPNSMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_protobuf_2fpb_5fmessage_2eproto() {
  delete PBAPNSUserInfo::default_instance_;
  delete PBAPNSUserInfo_reflection_;
  delete PBAPNSBody::default_instance_;
  delete PBAPNSBody_reflection_;
  delete PBAPNSMessage::default_instance_;
  delete PBAPNSMessage_reflection_;
}

void protobuf_AddDesc_protobuf_2fpb_5fmessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\031protobuf/pb_message.proto\022\007message\",\n\016"
    "PBAPNSUserInfo\022\013\n\003key\030\001 \002(\t\022\r\n\005value\030\002 \002"
    "(\t\"9\n\nPBAPNSBody\022\r\n\005alert\030\001 \001(\t\022\r\n\005sound"
    "\030\002 \001(\t\022\r\n\005badge\030\003 \001(\005\"\\\n\rPBAPNSMessage\022 "
    "\n\003aps\030\001 \002(\0132\023.message.PBAPNSBody\022)\n\010user"
    "Info\030\002 \003(\0132\027.message.PBAPNSUserInfoB\037\n\033c"
    "om.whosbean.qpush.protobufP\001", 268);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protobuf/pb_message.proto", &protobuf_RegisterTypes);
  PBAPNSUserInfo::default_instance_ = new PBAPNSUserInfo();
  PBAPNSBody::default_instance_ = new PBAPNSBody();
  PBAPNSMessage::default_instance_ = new PBAPNSMessage();
  PBAPNSUserInfo::default_instance_->InitAsDefaultInstance();
  PBAPNSBody::default_instance_->InitAsDefaultInstance();
  PBAPNSMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_protobuf_2fpb_5fmessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_protobuf_2fpb_5fmessage_2eproto {
  StaticDescriptorInitializer_protobuf_2fpb_5fmessage_2eproto() {
    protobuf_AddDesc_protobuf_2fpb_5fmessage_2eproto();
  }
} static_descriptor_initializer_protobuf_2fpb_5fmessage_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int PBAPNSUserInfo::kKeyFieldNumber;
const int PBAPNSUserInfo::kValueFieldNumber;
#endif  // !_MSC_VER

PBAPNSUserInfo::PBAPNSUserInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PBAPNSUserInfo::InitAsDefaultInstance() {
}

PBAPNSUserInfo::PBAPNSUserInfo(const PBAPNSUserInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PBAPNSUserInfo::SharedCtor() {
  _cached_size_ = 0;
  key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PBAPNSUserInfo::~PBAPNSUserInfo() {
  SharedDtor();
}

void PBAPNSUserInfo::SharedDtor() {
  if (key_ != &::google::protobuf::internal::kEmptyString) {
    delete key_;
  }
  if (value_ != &::google::protobuf::internal::kEmptyString) {
    delete value_;
  }
  if (this != default_instance_) {
  }
}

void PBAPNSUserInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PBAPNSUserInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PBAPNSUserInfo_descriptor_;
}

const PBAPNSUserInfo& PBAPNSUserInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protobuf_2fpb_5fmessage_2eproto();
  return *default_instance_;
}

PBAPNSUserInfo* PBAPNSUserInfo::default_instance_ = NULL;

PBAPNSUserInfo* PBAPNSUserInfo::New() const {
  return new PBAPNSUserInfo;
}

void PBAPNSUserInfo::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_key()) {
      if (key_ != &::google::protobuf::internal::kEmptyString) {
        key_->clear();
      }
    }
    if (has_value()) {
      if (value_ != &::google::protobuf::internal::kEmptyString) {
        value_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PBAPNSUserInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string key = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->key().data(), this->key().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_value;
        break;
      }

      // required string value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->value().data(), this->value().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PBAPNSUserInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string key = 1;
  if (has_key()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->key(), output);
  }

  // required string value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->value(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PBAPNSUserInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string key = 1;
  if (has_key()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  // required string value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->value(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PBAPNSUserInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string key = 1;
    if (has_key()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->key());
    }

    // required string value = 2;
    if (has_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->value());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBAPNSUserInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PBAPNSUserInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PBAPNSUserInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PBAPNSUserInfo::MergeFrom(const PBAPNSUserInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_key()) {
      set_key(from.key());
    }
    if (from.has_value()) {
      set_value(from.value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PBAPNSUserInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBAPNSUserInfo::CopyFrom(const PBAPNSUserInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBAPNSUserInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void PBAPNSUserInfo::Swap(PBAPNSUserInfo* other) {
  if (other != this) {
    std::swap(key_, other->key_);
    std::swap(value_, other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PBAPNSUserInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PBAPNSUserInfo_descriptor_;
  metadata.reflection = PBAPNSUserInfo_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PBAPNSBody::kAlertFieldNumber;
const int PBAPNSBody::kSoundFieldNumber;
const int PBAPNSBody::kBadgeFieldNumber;
#endif  // !_MSC_VER

PBAPNSBody::PBAPNSBody()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PBAPNSBody::InitAsDefaultInstance() {
}

PBAPNSBody::PBAPNSBody(const PBAPNSBody& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PBAPNSBody::SharedCtor() {
  _cached_size_ = 0;
  alert_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  sound_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  badge_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PBAPNSBody::~PBAPNSBody() {
  SharedDtor();
}

void PBAPNSBody::SharedDtor() {
  if (alert_ != &::google::protobuf::internal::kEmptyString) {
    delete alert_;
  }
  if (sound_ != &::google::protobuf::internal::kEmptyString) {
    delete sound_;
  }
  if (this != default_instance_) {
  }
}

void PBAPNSBody::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PBAPNSBody::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PBAPNSBody_descriptor_;
}

const PBAPNSBody& PBAPNSBody::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protobuf_2fpb_5fmessage_2eproto();
  return *default_instance_;
}

PBAPNSBody* PBAPNSBody::default_instance_ = NULL;

PBAPNSBody* PBAPNSBody::New() const {
  return new PBAPNSBody;
}

void PBAPNSBody::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_alert()) {
      if (alert_ != &::google::protobuf::internal::kEmptyString) {
        alert_->clear();
      }
    }
    if (has_sound()) {
      if (sound_ != &::google::protobuf::internal::kEmptyString) {
        sound_->clear();
      }
    }
    badge_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PBAPNSBody::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string alert = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_alert()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->alert().data(), this->alert().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_sound;
        break;
      }

      // optional string sound = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_sound:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sound()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->sound().data(), this->sound().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_badge;
        break;
      }

      // optional int32 badge = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_badge:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &badge_)));
          set_has_badge();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PBAPNSBody::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string alert = 1;
  if (has_alert()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->alert().data(), this->alert().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->alert(), output);
  }

  // optional string sound = 2;
  if (has_sound()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->sound().data(), this->sound().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->sound(), output);
  }

  // optional int32 badge = 3;
  if (has_badge()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->badge(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PBAPNSBody::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string alert = 1;
  if (has_alert()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->alert().data(), this->alert().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->alert(), target);
  }

  // optional string sound = 2;
  if (has_sound()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->sound().data(), this->sound().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->sound(), target);
  }

  // optional int32 badge = 3;
  if (has_badge()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->badge(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PBAPNSBody::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string alert = 1;
    if (has_alert()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->alert());
    }

    // optional string sound = 2;
    if (has_sound()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sound());
    }

    // optional int32 badge = 3;
    if (has_badge()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->badge());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBAPNSBody::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PBAPNSBody* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PBAPNSBody*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PBAPNSBody::MergeFrom(const PBAPNSBody& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_alert()) {
      set_alert(from.alert());
    }
    if (from.has_sound()) {
      set_sound(from.sound());
    }
    if (from.has_badge()) {
      set_badge(from.badge());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PBAPNSBody::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBAPNSBody::CopyFrom(const PBAPNSBody& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBAPNSBody::IsInitialized() const {

  return true;
}

void PBAPNSBody::Swap(PBAPNSBody* other) {
  if (other != this) {
    std::swap(alert_, other->alert_);
    std::swap(sound_, other->sound_);
    std::swap(badge_, other->badge_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PBAPNSBody::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PBAPNSBody_descriptor_;
  metadata.reflection = PBAPNSBody_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PBAPNSMessage::kApsFieldNumber;
const int PBAPNSMessage::kUserInfoFieldNumber;
#endif  // !_MSC_VER

PBAPNSMessage::PBAPNSMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PBAPNSMessage::InitAsDefaultInstance() {
  aps_ = const_cast< ::message::PBAPNSBody*>(&::message::PBAPNSBody::default_instance());
}

PBAPNSMessage::PBAPNSMessage(const PBAPNSMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PBAPNSMessage::SharedCtor() {
  _cached_size_ = 0;
  aps_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PBAPNSMessage::~PBAPNSMessage() {
  SharedDtor();
}

void PBAPNSMessage::SharedDtor() {
  if (this != default_instance_) {
    delete aps_;
  }
}

void PBAPNSMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PBAPNSMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PBAPNSMessage_descriptor_;
}

const PBAPNSMessage& PBAPNSMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protobuf_2fpb_5fmessage_2eproto();
  return *default_instance_;
}

PBAPNSMessage* PBAPNSMessage::default_instance_ = NULL;

PBAPNSMessage* PBAPNSMessage::New() const {
  return new PBAPNSMessage;
}

void PBAPNSMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_aps()) {
      if (aps_ != NULL) aps_->::message::PBAPNSBody::Clear();
    }
  }
  userinfo_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PBAPNSMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .message.PBAPNSBody aps = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_aps()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_userInfo;
        break;
      }

      // repeated .message.PBAPNSUserInfo userInfo = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_userInfo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_userinfo()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_userInfo;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PBAPNSMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .message.PBAPNSBody aps = 1;
  if (has_aps()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->aps(), output);
  }

  // repeated .message.PBAPNSUserInfo userInfo = 2;
  for (int i = 0; i < this->userinfo_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->userinfo(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PBAPNSMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .message.PBAPNSBody aps = 1;
  if (has_aps()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->aps(), target);
  }

  // repeated .message.PBAPNSUserInfo userInfo = 2;
  for (int i = 0; i < this->userinfo_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->userinfo(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PBAPNSMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .message.PBAPNSBody aps = 1;
    if (has_aps()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->aps());
    }

  }
  // repeated .message.PBAPNSUserInfo userInfo = 2;
  total_size += 1 * this->userinfo_size();
  for (int i = 0; i < this->userinfo_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->userinfo(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBAPNSMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PBAPNSMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PBAPNSMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PBAPNSMessage::MergeFrom(const PBAPNSMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  userinfo_.MergeFrom(from.userinfo_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_aps()) {
      mutable_aps()->::message::PBAPNSBody::MergeFrom(from.aps());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PBAPNSMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBAPNSMessage::CopyFrom(const PBAPNSMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBAPNSMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  for (int i = 0; i < userinfo_size(); i++) {
    if (!this->userinfo(i).IsInitialized()) return false;
  }
  return true;
}

void PBAPNSMessage::Swap(PBAPNSMessage* other) {
  if (other != this) {
    std::swap(aps_, other->aps_);
    userinfo_.Swap(&other->userinfo_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PBAPNSMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PBAPNSMessage_descriptor_;
  metadata.reflection = PBAPNSMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace message

// @@protoc_insertion_point(global_scope)
