// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_message.proto

package com.argo.qpush.protobuf;

public interface PBAPNSEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.PBAPNSEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 op = 1;</code>
   */
  boolean hasOp();
  /**
   * <code>required int32 op = 1;</code>
   */
  int getOp();

  /**
   * <code>required string token = 2;</code>
   */
  boolean hasToken();
  /**
   * <code>required string token = 2;</code>
   */
  java.lang.String getToken();
  /**
   * <code>required string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>required string appKey = 3;</code>
   */
  boolean hasAppKey();
  /**
   * <code>required string appKey = 3;</code>
   */
  java.lang.String getAppKey();
  /**
   * <code>required string appKey = 3;</code>
   */
  com.google.protobuf.ByteString
      getAppKeyBytes();

  /**
   * <code>required string userId = 4;</code>
   */
  boolean hasUserId();
  /**
   * <code>required string userId = 4;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>required string userId = 4;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>required int32 typeId = 5;</code>
   */
  boolean hasTypeId();
  /**
   * <code>required int32 typeId = 5;</code>
   */
  int getTypeId();

  /**
   * <code>optional int32 read = 6;</code>
   */
  boolean hasRead();
  /**
   * <code>optional int32 read = 6;</code>
   */
  int getRead();

  /**
   * <code>optional string deviceId = 7;</code>
   */
  boolean hasDeviceId();
  /**
   * <code>optional string deviceId = 7;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <code>optional string deviceId = 7;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();
}
