// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_message.proto

package com.argo.qpush.protobuf;

/**
 * Protobuf type {@code message.PBAPNSBody}
 */
public  final class PBAPNSBody extends
    com.google.protobuf.GeneratedMessage
    implements PBAPNSBodyOrBuilder {
  // Use PBAPNSBody.newBuilder() to construct.
  private PBAPNSBody(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private PBAPNSBody(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final PBAPNSBody defaultInstance;
  public static PBAPNSBody getDefaultInstance() {
    return defaultInstance;
  }

  public PBAPNSBody getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private PBAPNSBody(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            alert_ = input.readBytes();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            sound_ = input.readBytes();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            badge_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.argo.qpush.protobuf.PbMessage.internal_static_message_PBAPNSBody_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.argo.qpush.protobuf.PbMessage.internal_static_message_PBAPNSBody_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.argo.qpush.protobuf.PBAPNSBody.class, com.argo.qpush.protobuf.PBAPNSBody.Builder.class);
  }

  public static com.google.protobuf.Parser<PBAPNSBody> PARSER =
      new com.google.protobuf.AbstractParser<PBAPNSBody>() {
    public PBAPNSBody parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PBAPNSBody(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<PBAPNSBody> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional string alert = 1;
  public static final int ALERT_FIELD_NUMBER = 1;
  private java.lang.Object alert_;
  /**
   * <code>optional string alert = 1;</code>
   */
  public boolean hasAlert() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string alert = 1;</code>
   */
  public java.lang.String getAlert() {
    java.lang.Object ref = alert_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        alert_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string alert = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAlertBytes() {
    java.lang.Object ref = alert_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alert_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string sound = 2;
  public static final int SOUND_FIELD_NUMBER = 2;
  private java.lang.Object sound_;
  /**
   * <code>optional string sound = 2;</code>
   */
  public boolean hasSound() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string sound = 2;</code>
   */
  public java.lang.String getSound() {
    java.lang.Object ref = sound_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        sound_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string sound = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSoundBytes() {
    java.lang.Object ref = sound_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sound_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional int32 badge = 3;
  public static final int BADGE_FIELD_NUMBER = 3;
  private int badge_;
  /**
   * <code>optional int32 badge = 3;</code>
   */
  public boolean hasBadge() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional int32 badge = 3;</code>
   */
  public int getBadge() {
    return badge_;
  }

  private void initFields() {
    alert_ = "";
    sound_ = "";
    badge_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getAlertBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getSoundBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, badge_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getAlertBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getSoundBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, badge_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.argo.qpush.protobuf.PBAPNSBody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.argo.qpush.protobuf.PBAPNSBody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.argo.qpush.protobuf.PBAPNSBody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.argo.qpush.protobuf.PBAPNSBody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.argo.qpush.protobuf.PBAPNSBody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.argo.qpush.protobuf.PBAPNSBody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.argo.qpush.protobuf.PBAPNSBody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.argo.qpush.protobuf.PBAPNSBody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.argo.qpush.protobuf.PBAPNSBody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.argo.qpush.protobuf.PBAPNSBody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.argo.qpush.protobuf.PBAPNSBody prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code message.PBAPNSBody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.argo.qpush.protobuf.PBAPNSBodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.argo.qpush.protobuf.PbMessage.internal_static_message_PBAPNSBody_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.argo.qpush.protobuf.PbMessage.internal_static_message_PBAPNSBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.argo.qpush.protobuf.PBAPNSBody.class, com.argo.qpush.protobuf.PBAPNSBody.Builder.class);
    }

    // Construct using com.argo.qpush.protobuf.PBAPNSBody.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      alert_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      sound_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      badge_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.argo.qpush.protobuf.PbMessage.internal_static_message_PBAPNSBody_descriptor;
    }

    public com.argo.qpush.protobuf.PBAPNSBody getDefaultInstanceForType() {
      return com.argo.qpush.protobuf.PBAPNSBody.getDefaultInstance();
    }

    public com.argo.qpush.protobuf.PBAPNSBody build() {
      com.argo.qpush.protobuf.PBAPNSBody result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.argo.qpush.protobuf.PBAPNSBody buildPartial() {
      com.argo.qpush.protobuf.PBAPNSBody result = new com.argo.qpush.protobuf.PBAPNSBody(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.alert_ = alert_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.sound_ = sound_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.badge_ = badge_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.argo.qpush.protobuf.PBAPNSBody) {
        return mergeFrom((com.argo.qpush.protobuf.PBAPNSBody)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.argo.qpush.protobuf.PBAPNSBody other) {
      if (other == com.argo.qpush.protobuf.PBAPNSBody.getDefaultInstance()) return this;
      if (other.hasAlert()) {
        bitField0_ |= 0x00000001;
        alert_ = other.alert_;
        onChanged();
      }
      if (other.hasSound()) {
        bitField0_ |= 0x00000002;
        sound_ = other.sound_;
        onChanged();
      }
      if (other.hasBadge()) {
        setBadge(other.getBadge());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.argo.qpush.protobuf.PBAPNSBody parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.argo.qpush.protobuf.PBAPNSBody) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional string alert = 1;
    private java.lang.Object alert_ = "";
    /**
     * <code>optional string alert = 1;</code>
     */
    public boolean hasAlert() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string alert = 1;</code>
     */
    public java.lang.String getAlert() {
      java.lang.Object ref = alert_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        alert_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string alert = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAlertBytes() {
      java.lang.Object ref = alert_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alert_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string alert = 1;</code>
     */
    public Builder setAlert(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      alert_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string alert = 1;</code>
     */
    public Builder clearAlert() {
      bitField0_ = (bitField0_ & ~0x00000001);
      alert_ = getDefaultInstance().getAlert();
      onChanged();
      return this;
    }
    /**
     * <code>optional string alert = 1;</code>
     */
    public Builder setAlertBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      alert_ = value;
      onChanged();
      return this;
    }

    // optional string sound = 2;
    private java.lang.Object sound_ = "";
    /**
     * <code>optional string sound = 2;</code>
     */
    public boolean hasSound() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string sound = 2;</code>
     */
    public java.lang.String getSound() {
      java.lang.Object ref = sound_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        sound_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sound = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSoundBytes() {
      java.lang.Object ref = sound_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sound_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sound = 2;</code>
     */
    public Builder setSound(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      sound_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sound = 2;</code>
     */
    public Builder clearSound() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sound_ = getDefaultInstance().getSound();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sound = 2;</code>
     */
    public Builder setSoundBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      sound_ = value;
      onChanged();
      return this;
    }

    // optional int32 badge = 3;
    private int badge_ ;
    /**
     * <code>optional int32 badge = 3;</code>
     */
    public boolean hasBadge() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 badge = 3;</code>
     */
    public int getBadge() {
      return badge_;
    }
    /**
     * <code>optional int32 badge = 3;</code>
     */
    public Builder setBadge(int value) {
      bitField0_ |= 0x00000004;
      badge_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 badge = 3;</code>
     */
    public Builder clearBadge() {
      bitField0_ = (bitField0_ & ~0x00000004);
      badge_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:message.PBAPNSBody)
  }

  static {
    defaultInstance = new PBAPNSBody(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:message.PBAPNSBody)
}

