// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_message.proto

package com.argo.qpush.protobuf;

public interface PBAPNSUserInfoOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required string key = 1;
  /**
   * <code>required string key = 1;</code>
   */
  boolean hasKey();
  /**
   * <code>required string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>required string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  // required string value = 2;
  /**
   * <code>required string value = 2;</code>
   */
  boolean hasValue();
  /**
   * <code>required string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>required string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
