// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/pb_message.proto

package com.argo.qpush.protobuf;

public interface PBAPNSMessageOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required .message.PBAPNSBody aps = 1;
  /**
   * <code>required .message.PBAPNSBody aps = 1;</code>
   */
  boolean hasAps();
  /**
   * <code>required .message.PBAPNSBody aps = 1;</code>
   */
  com.argo.qpush.protobuf.PBAPNSBody getAps();
  /**
   * <code>required .message.PBAPNSBody aps = 1;</code>
   */
  com.argo.qpush.protobuf.PBAPNSBodyOrBuilder getApsOrBuilder();

  // repeated .message.PBAPNSUserInfo userInfo = 2;
  /**
   * <code>repeated .message.PBAPNSUserInfo userInfo = 2;</code>
   */
  java.util.List<com.argo.qpush.protobuf.PBAPNSUserInfo>
      getUserInfoList();
  /**
   * <code>repeated .message.PBAPNSUserInfo userInfo = 2;</code>
   */
  com.argo.qpush.protobuf.PBAPNSUserInfo getUserInfo(int index);
  /**
   * <code>repeated .message.PBAPNSUserInfo userInfo = 2;</code>
   */
  int getUserInfoCount();
  /**
   * <code>repeated .message.PBAPNSUserInfo userInfo = 2;</code>
   */
  java.util.List<? extends com.argo.qpush.protobuf.PBAPNSUserInfoOrBuilder>
      getUserInfoOrBuilderList();
  /**
   * <code>repeated .message.PBAPNSUserInfo userInfo = 2;</code>
   */
  com.argo.qpush.protobuf.PBAPNSUserInfoOrBuilder getUserInfoOrBuilder(
      int index);
}
