// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_message.proto

package com.argo.qpush.protobuf;

public interface PBAPNSUserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:message.PBAPNSUserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string key = 1;</code>
   */
  boolean hasKey();
  /**
   * <code>required string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <code>required string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>required string value = 2;</code>
   */
  boolean hasValue();
  /**
   * <code>required string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <code>required string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
